site_name: Wiki
site_url: https://wiki.swecc.org
repo_url: https://github.com/swecc-uw/swecc-wiki

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    scheme: slate # dark mode as default
    primary: custom
    accent: custom
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Member Resources:
      - Overview: member-resources/index.md
      - Recruiting:
          - Job Search:
              - Overview: member-resources/applying-to-jobs/index.md
              - Finding Job Applications: member-resources/applying-to-jobs/finding-job-applications.md
          - Interview Preparation:
              - Overview: member-resources/interview-prep/index.md
              - Behavioral Interviews:
                  - Overview: member-resources/interview-prep/behavioral/index.md
              - Technical Interviews:
                  - Overview: member-resources/interview-prep/technical/index.md
                  - Data Structures and Algorithms (Leetcode) Interviews: member-resources/interview-prep/technical/dsa.md
                  - System Design Interviews: member-resources/interview-prep/technical/sys-design-interviews.md
                  - System Design Primer: member-resources/interview-prep/technical/sys-design-primer.md
      - Succeeding at Your Internship:
          - Your First Internship: member-resources/succeeding-at-your-internship/index.md
      - Contributing to Open Source: member-resources/contributing-to-open-source/index.md
  - Engineering:
      - Overview: engineering/index.md
      - Technical Documentation:
          - Coming Soon: engineering/placeholder.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: true
      href: "mailto:{email}"
      count_empty_lines: true
      fallback_to_empty: false
      enabled: true
